# Generated by Django 3.2.6 on 2021-09-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210903_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectslist',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='project_pics'),
        ),
    ]
