# Generated by Django 3.2.7 on 2021-11-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20211102_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectslist',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
