# Generated by Django 3.2.7 on 2021-11-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_projectslist_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectslist',
            name='end_date',
            field=models.DateField(),
        ),
    ]
