# Generated by Django 4.0.5 on 2022-08-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_projectslist_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectslist',
            name='html_files',
            field=models.FileField(blank=True, default=None, null=True, upload_to='html_files'),
        ),
    ]
