# Generated by Django 4.0.5 on 2022-08-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_projectslist_html_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectslist',
            old_name='description',
            new_name='short_description',
        ),
    ]
