# Generated by Django 3.2.7 on 2021-09-10 14:56

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogsList',
            fields=[
                ('postId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('blogHeaderImage', django_resized.forms.ResizedImageField(crop=None, default='default.jpg', force_format='JPEG', keep_meta=True, quality=85, size=[500, 500], upload_to='blog_pics')),
                ('content', models.TextField()),
                ('publishedDate', models.DateTimeField()),
                ('isModified', models.BooleanField(default=False)),
                ('modifiedDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'blogs',
            },
        ),
    ]
