# Generated by Django 3.2.7 on 2021-09-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogslist',
            name='modifiedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
