# Generated by Django 3.2.7 on 2021-09-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogslist_modifieddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogslist',
            name='modifiedDate',
            field=models.DateTimeField(),
        ),
    ]
